export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_ANSWERS = 'ADD_ANSWERS';

export const INCREASE_LIKES = 'INCREASE_ANSWER_LIKES';
export const INCREASE_LIKES_BY = 'INCREASE_ANSWER_LIKES_BY';

export const EDIT_ANSWER = 'EDIT_ANSWER';

export const REMOVE_ANSWER = 'REMOVE_ANSWER';
export const REMOVE_ANSWERS = 'REMOVE_ANSWERS';

export const DECREASE_LIKES = 'DECREASE_ANSWER_LIKES';
// TODO REMOVE_LIKES

export const SET_HAS_LIKED = 'SET_HAS_ANSWER_LIKED';
export const SET_LIKES = 'SET_ANSWER_LIKES';
