export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';

export const ADD_ANSWER = 'ADD_ANSWER_TO_QUESTION';
// TODO export const ADD_ANSWERS = 'ADD_ANSWERS_TO_QUESTION';

export const INCREASE_LIKES = 'INCREASE_QUESTION_LIKES';
export const INCREASE_LIKES_BY = 'INCREASE_QUESTION_LIKES_BY';

export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_QUESTIONS = 'REMOVE_QUESTIONS';

export const REMOVE_ANSWER = 'REMOVE_ANSWER_FROM_QUESTION';
export const REMOVE_ANSWERS = 'REMOVE_ANSWERS_FROM_QUESTION';

export const DECREASE_LIKES = 'DECREASE_QUESTION_LIKES';
export const DECREASE_LIKES_BY = 'DECREASE_QUESTION_LIKES_BY';

export const SET_HAS_LIKED = 'SET_HAS_QUESTION_LIKED';
export const SET_LIKES = 'SET_QUESTION_LIKES';
