export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';

export const ADD_ANSWER = 'ADD_ANSWER_TO_QUESTION';
// TODO export const ADD_ANSWERS = 'ADD_ANSWERS_TO_QUESTION';

export const ADD_LIKE = 'ADD_LIKE_TO_QUESTION';
export const ADD_LIKES = 'ADD_LIKES_TO_QUESTION';

export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_QUESTIONS = 'REMOVE_QUESTIONS';

export const REMOVE_ANSWER = 'REMOVE_ANSWER_FROM_QUESTION';
export const REMOVE_ANSWERS = 'REMOVE_ANSWERS_FROM_QUESTION';

export const REMOVE_LIKE = 'REMOVE_LIKE_FROM_QUESTION';
export const REMOVE_LIKES = 'REMOVE_LIKES_FROM_QUESTION';
